import type { Metadata } from "next";
import { ReactQueryClientProvider } from "@/provider/ReactQueryClient";
import "./globals.css";
import localFont from "next/font/local";

import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const myFont = localFont({
  src: [
    { path: "../../public/fonts/NanumMyeongjo.woff" },
    { path: "../../public/fonts/PretendardVariable.woff2" },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.className} bg-neutral-100`}>
        <Navbar />
        <ReactQueryClientProvider>{children}</ReactQueryClientProvider>
      </body>
    </html>
  );
}
