import type { Metadata } from "next";
import { ReactQueryClientProvider } from "@/src/provider/ReactQueryClient";
import "./globals.css";
import localFont from 'next/font/local'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const myFont = localFont({src: '../../public/fonts/PretendardVariable.woff2'})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.className} bg-neutral-100`}>
        <ReactQueryClientProvider>{children}</ReactQueryClientProvider>
      </body>
    </html>
  );
}
